import '@repo/ui/text-styles';
import LocaleSwitcher from '@/components/LocaleSwitcher';
import type { Metadata } from 'next';
import Link from 'next/link';
import ThemeSelector from '@/components/ThemeSelector';
import NextThemeProvider from '@/lib/NextThemeProviders';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale}>
      <body>
        <NextThemeProvider>
          <nav>
            <Link href={`/${locale}`}>Home</Link>
            <LocaleSwitcher />

            {/* 추후 라이트 색상 추가 시 추가 */}
            {/* <ThemeSelector /> */}
          </nav>
          {children}
        </NextThemeProvider>
      </body>
    </html>
  );
}

// ✨ [2024.4.2 기준] next-intl에서 아직 SSG를 지원하지 않음 -> 지원하면 SSG로 변환
// ```pnpm build``` 실패, 즉 production build 실패
// export async function generateStaticParams() {
//   return [{ locale: 'ko' }, { locale: 'en' }];
// }
